import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The resource sidebar is generated entirely from the docs/ folder structure.
// Ordering and labels come from each folder's _category_.json and each page's
// sidebar_position / sidebar_label front matter.
const sidebars: SidebarsConfig = {
  resourceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
